# Created by trellis-cli v1.9.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  nikodim.lv:
    site_hosts:
    - canonical: www.nikodim.lv
      redirects:
      - nikodim.lv
    local_path: ../site
    branch: master
    repo: git@github.com:deadly-sun/nikodim.lv.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
